### ISSUE TITLE
List of employee rewards

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Process-Documentation#10]

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=1Yf-QLGpCJopzxWAQl5XGgSW2fGYbx6d9CJgnwjMLYyQ&authuser=0

**Comment by anujkhurana** [comment]
Sorry if I wasn't specific. But will like this to have amounts as well.

**Comment by Tanvi-HR** [comment]
Amounts updated.

**Comment by Tanvi-HR** [comment]
Caculo mall has gift vouchers worth  Rs. 250/-, ​500/- & 1000/- & Westside vouchers.

Grand Hayat , Taj, Coastal Honda & Ford purchase these vouchers for staff as well as customers.

**Comment by Tanvi-HR** [comment]
These vouchers can be used through out the mall.

**Comment by Tanvi-HR** [comment]
Do you want to consider Sodexo?

**Comment by anujkhurana** [comment]
No. Sodexho is not fun.

**Comment by Tanvi-HR** [comment]
Out of all I have spoken to, Aroma Thai has agreed to give discount if we buy vouchers in bulk. Their foot massage rates start from Rs.1150. Combo of Head & Foot Massage is Rs.2100. 

If vouchers bought are more than 2k, he'll give 20% discount. If more than 5k then 30%. 

They don't have a soft copy of the rate card, we'll have to go there and see.

**Comment by Tanvi-HR** [comment]
Contact person is Ashant : 0832 2423277.

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=169PtoY3QFbsoq39F6ONzx5lAY6K-rvlM9eSlCxPS2NU&authuser=0

Cover letter for rewards.
