### ISSUE TITLE
Budget / expense template

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Process-Documentation#11]

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=1IjleVQ14IcMqL-rmUPgwspPISXtKLELhhhyh7j0hoVk&authuser=0

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=1IjleVQ14IcMqL-rmUPgwspPISXtKLELhhhyh7j0hoVk&authuser=0

**Comment by anujkhurana** [comment]
Looks good. Let's use this sheet to track all expenses that we do as a
company except salaries.

Once we have 3 month data here let's then make a budget.

Works?

**Comment by Tanvi-HR** [comment]
Sure.. will start adding components from Petty cash and other values I know. I have not included staff salaries in the budget, mentioned only Preeti's salary component.

**Comment by Tanvi-HR** [comment]
https://docs.google.com/a/ajency.in/spreadsheets/d/1IjleVQ14IcMqL-rmUPgwspPISXtKLELhhhyh7j0hoVk/edit#gid=0

1st sheet (Expenses) is where the summary will appear. 
Separate sheet for each type of expense will be maintained. 
Individual sheet will have bill / receipt against the amount. 

Format tables are added for first few components. Pls review and tell me if this format works.

**Comment by anujkhurana** [comment]
Very impressive. Have a couple of questions. Let's discuss when you are
back.

**Comment by Tanvi-HR** [comment]
Pls refer the same sheet for changes. 

I have added activity master sheet where all entries will be made. You select month and category from the drop down menu, enter party name and amount. Based on that there is another sheet called Pivot Table where report will be generated. 

We can add another column for bill copy and this will not be included in the pivot table report.  
Let me know if this works, I will figure out a way to add cash flow in this.

**Comment by Tanvi-HR** [comment]
We get 2 totals - Per category for entire year and per month for all categories
