### ISSUE TITLE
Design Leave Policy

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Process-Documentation#8]

**Comment by Tanvi-HR** [comment]
Leave Rules as per SE Act

Casual Leave: 6 days during the first 12 months and subsequent years cannot be accumulated.
Wages need not be paid for unavailed leave.

Sick Leave: 9 days during the first 12 months and subsequent years cannot be accumulated.
Wages need not be paid for unavailed leave.

Privilege Leave: 15 days in the subsequent year, if worked for 240 days or more in a continuous period of 12 months. Can be accumulated up to 45 days. Wages to be paid for unavailed leave, if the employees quits employment.

**Comment by Tanvi-HR** [comment]
N & F HOLIDAYS 7 days including 26th jan, 1st may, 15th Aug, 2nd oct and 19th Dec.

**Comment by Tanvi-HR** [comment]
For specifically leave application, can we have like an online calender? 

So it can list names of employees and a calender. Employees can request for leave by selecting dates, select type of leave and reason. Once approved - the color of the cell can change. 
All the employees should be able to view everyone's leaves to plan work accordingly.

**Comment by avantih** [comment]
Sounds good!
